# App
spring.application.name=expensewise
server.port=8085

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/expensewise_db
spring.datasource.username=root
spring.datasource.password=1234


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=expensewise_super_secret_key_teja_2025_make_it_long
jwt.expiration=86400000

